// Generado automáticamente - 2026-06-08 23:07:45
const DASHBOARD_DATA = {
    "last_updated": "08/06/2026 23:07:45",
    "storage_limit_gb": 10.0,
    "storage_used_bytes": 0,
    "s3_bucket": "Sin configurar",
    "s3_endpoint": "Amazon S3",
    "region": "us-west-2",
    "files_count": 0,
    "repositories": [
        {
            "name": "agente24-web-chat",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "angular-school-c1",
            "branch": "master",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Animaciones",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "api-disney",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "api-dragon-ball",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "api-pokemon",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "api-rickandmortyapi",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "astroship_website",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "banner--linkedln",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Checkpoints-M1",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "click-to-component",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "clinica-odontologica",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "clinica1806",
            "branch": "appmod/java-upgrade-20260520220247",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "clinica1806-View",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "credenciales-escolares",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "ctd-fe3-clase-16",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Curso-JavaScript",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "cvless_webside",
            "branch": "master",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "dashboard-git",
            "branch": "main",
            "status": "dirty",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 1,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Deportes",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "DG-BaseDatos-B2",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "DG-Imperativa-B2",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "DG-Translazaro",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "DH-Frontend-B1",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "DH-Informatica-B1",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "draw.oi",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "ejercicio-formulario-js",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "ejercicio-login-storage",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "fe3-final",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "FEII-C5-raulgm00",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "flexdu",
            "branch": "next",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Garcia_Raul_Rosero_Ricardo",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "I-parcial-frontend-III",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "IJ-SpringBoot",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Imperativa-C5-RaulGarcia-B2",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Instagram",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "jscamp",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "licencias-escolares",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "map",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "my-web-coffe",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "my-web-person",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Paleteria",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Parallax-Empresa",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Parallax-Master",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "pga-connect",
            "branch": "feature/backend-saas-architecture",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "porta-retratos",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Portafolio",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "practicando-JSON",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "Project-00-ToDoList",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "propuestas-wesoft",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "quarkus-api-pacientes",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "raul.garcia.developer.com.v1",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "React-Examen-Parcial-I",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "revelacion",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "spring-bot-web-t-mplate-pro",
            "branch": "master",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "template_html",
            "branch": "master",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "tienda",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "trabajo-actividades-iz",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "UDE-JavaEE2",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "UDE-JavaScript",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "web-caledoscopio",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        },
        {
            "name": "web-cv-deportivo",
            "branch": "main",
            "status": "clean",
            "remote_status": "synced",
            "ahead_count": 0,
            "behind_count": 0,
            "uncommitted_changes_count": 0,
            "is_dubious": false,
            "error": null
        }
    ],
    "s3_files": []
};
